### ISSUE TITLE
非常赞的项目, 希望能和 ssdb 自带的 php api 兼容

### ISSUE THREAD

**Issue by ideawu** [jonnywang/phpssdb#1]
可以用 https://github.com/ideawu/ssdb/blob/master/tools/unittest.php 来跑测试.

**Comment by jonnywang** [comment]
感谢支持，已经在写test和document了,我会尽力与官方phpssdb类接口保持一致

**Comment by ideawu** [comment]
可以不要着急 close issue, 等最终解决了再 close.

**Comment by jonnywang** [comment]
所提都已经解决了

**Comment by ideawu** [comment]
请确保 unittest.php 能够执行!
