### ISSUE TITLE
PHP 7.0 build fail.

### ISSUE THREAD

**Issue by gzanthony** [jonnywang/phpssdb#10]
/bin/bash /opt/phpssdb/libtool --mode=compile cc  -I. -I/opt/phpssdb -DPHP_ATOM_INC -I/opt/phpssdb/include -I/opt/phpssdb/main -I/opt/phpssdb -I/usr/local/swoole/include/php -I/usr/local/swoole/include/php/main -I/usr/local/swoole/include/php/TSRM -I/usr/local/swoole/include/php/Zend -I/usr/local/swoole/include/php/ext -I/usr/local/swoole/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/phpssdb/ssdb_library.c -o ssdb_library.lo 
 cc -I. -I/opt/phpssdb -DPHP_ATOM_INC -I/opt/phpssdb/include -I/opt/phpssdb/main -I/opt/phpssdb -I/usr/local/swoole/include/php -I/usr/local/swoole/include/php/main -I/usr/local/swoole/include/php/TSRM -I/usr/local/swoole/include/php/Zend -I/usr/local/swoole/include/php/ext -I/usr/local/swoole/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/phpssdb/ssdb_library.c  -fPIC -DPIC -o .libs/ssdb_library.o
/opt/phpssdb/ssdb_library.c:21:40: fatal error: ext/standard/php_smart_str.h: 没有那个文件或目录
compilation terminated.
Makefile:193: recipe for target 'ssdb_library.lo' failed
make: *** [ssdb_library.lo] Error 1

**Comment by gzanthony** [comment]
我用 php 7.0 去编译插件，结果说找不到一个库文件，所以想问一下这个该如何解决？

**Comment by jonnywang** [comment]
用的时分支版本吗？
