### ISSUE TITLE
hset返回值问题

### ISSUE THREAD

**Issue by zh-xg** [jonnywang/phpssdb#14]
hset一个不存在的key时成功返回true
hset一个存在的key时成功总返回false
到底要如何界定操作成功还是失败？

**Comment by jonnywang** [comment]
ssdb-server 1.9.2
```
telnet 127.0.0.1 8888

4
hset
4
user
4
good
1
a

2
ok
1
1

4
hset
4
user
4
good
1
b

2
ok
1
0

4
hset
4
user
4
good
2
aa

2
ok
1
0
```
测试发现与官网文档说明不符 http://ssdb.io/docs/zh_cn/commands/hset.html，所以对于客户端来说无法判定是否成功，请到ssdb提issue
