### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by stephenyaoshun** [jonnywang/phpssdb#15]
/root/phpssdb/ssdb.c:42: error: ‘PHP_FE_END’ undeclared here (not in a function)
make: *** [ssdb.lo] Error 1

**Comment by ixqbar** [comment]
php版本太低，请升级php版本

懒得升级时请修改ssdb.c:42请替换PHP_FE_END为{NULL, NULL, NULL}
或者
```
#if (defined(PHP_VERSION_ID) && PHP_VERSION_ID >= 50307)
    PHP_FE_END
#else
    {NULL, NULL, NULL}
#endif
```
不保证php低版本适用phpssdb还有其他未知兼容错误
