### ISSUE TITLE
hset如果key已存在，永远返回false

### ISSUE THREAD

**Issue by jilieryuyi** [jonnywang/phpssdb#19]
echo "hset" . PHP_EOL;
$result = $ssdb_handle->hset("blog_list", "1", "1");
var_dump($result);
$result = $ssdb_handle->hset("blog_list", "1", "2");
var_dump($result);

运行第一次
true
false

运行第二次
false
false

运行第三次
false
false

....

如题！

**Comment by ixqbar** [comment]
请参考官网返回码 http://ssdb.io/docs/commands/hset.html
