### ISSUE TITLE
php7.4 报错

### ISSUE THREAD

**Issue by zhangluofeng** [jonnywang/phpssdb#21]
/usr/local/src/phpssdb/ssdb_class.c: 在函数‘register_ssdb_class’中:
/usr/local/src/phpssdb/ssdb_class.c:3687:2: 错误：提供给函数‘zend_register_class_alias_ex’的实参太少
  zend_register_class_alias_ex(ZEND_STRL("SimpleSSDB"), ssdb_ce TSRMLS_CC);
  ^
In file included from /usr/local/include/php/main/php.h:37:0,
                 from /usr/local/src/phpssdb/ssdb_class.c:19:
/usr/local/include/php/Zend/zend_API.h:287:14: 附注：在此声明
 ZEND_API int zend_register_class_alias_ex(const char *name, size_t name_len, zend_class_entry *ce, int persistent);
              ^
make: *** [ssdb_class.lo] 错误 1

**Comment by ixqbar** [comment]
@zhangluofeng updated

thanks
