### ISSUE TITLE
出现 segmentation fault

### ISSUE THREAD

**Issue by vlike** [jonnywang/phpssdb#5]
代码大概如下：

$xx = array(
	'abc',
	'abc',
	'abc',
	'abc',
);

$data = $db->multi_hset('test', $xx);

测试环境
mac 10.10
PHP 5.5.20

[1]    77119 segmentation fault  php kk.php

**Comment by vlike** [comment]
测试过，大约的问题是不能用  数字 作为 数组的key，无论是 8 或者 '8' 这样都不行，坐等大神修复，不知道其它方法有没有此问题

**Comment by vlike** [comment]
测试过，大约的问题是不能用  数字 作为 数组的key，无论是 8 或者 '8' 这样都不行，坐等大神修复，不知道其它方法有没有此问题

**Comment by jonnywang** [comment]
fixed

请更新

**Comment by vlike** [comment]
神一样的速度~感谢

**Comment by jonnywang** [comment]
感谢你的反馈
