### ISSUE TITLE
请问如何判断读写操作失败？

### ISSUE THREAD

**Issue by vlike** [jonnywang/phpssdb#6]
好像取得空数据时，失败时，还有写入成功时，都反回NULL，这样比较难判断成功失败，
建议增加失败时的返回值

**Comment by jonnywang** [comment]
写入成功时怎么会返回NULL呢，请提供测试代码

**Comment by vlike** [comment]
认真检查了一下，是我的代码有问题，Sorry。写入的返回没有问题。

那读取时呢？建议把失败时的返回值设成其它

**Comment by jonnywang** [comment]
请提供测试代码
