### ISSUE TITLE
安装失败, 不知道缺少什么库

### ISSUE THREAD

**Issue by gqkang** [jonnywang/phpssdb#7]
ssdb_library.c:93:3: error: use of undeclared identifier 'tsrm_ls'   php_stream_close(ssdb_sock->stream);

nclude/php/main/php_streams.h:283:83: note: expanded from macro 'php_stream_close'
#define php_stream_close(stream)        _php_stream_free((stream), PHP_STREAM_FREE_CLOSE TSRMLS_CC)

**Comment by jonnywang** [comment]
don't use --enable-maintainer-zts
