### ISSUE TITLE
hgetall truncates keys with binary values

### ISSUE THREAD

**Issue by mxleads** [jonnywang/phpssdb#8]
Using hgetall will truncate values containing binary encoding presumably due to line break detection bug. When requesting using standard hget($key,'r') the bug does not occur.

	$ssdb_simple = new SimpleSSDB('10.0.0.1',8888); // Native PHP class
	$redis = new Redis();// Redis C extension
	$ssdb = new SSDB();// phpssdb C extension
	$ssdb->connect('10.0.0.1', 8888);
	$redis->connect('10.0.0.1', 8888);
	$response = $ssdb->hgetall($key);
	print_r($response);

	$response = $ssdb_simple->hgetall($key);
	print_r($response);

	$response = $redis->hgetall($key);
	print_r($response);

Produces

Array
(
    [r] => ??? alt2.gmail-smtp-in.l.google.com?!
    [s] => 
)
Array
(
    [r] => ??? alt2.gmail-smtp-in.l.google.com?!3~!4j!? z^1j=
    [s] => A
)
Array
(
    [r] => ??? alt2.gmail-smtp-in.l.google.com?!3~!4j!? z^1j=
    [s] => A
)

**Comment by jonnywang** [comment]
thanks for your issue!

i fixed it!

please update!
